# Generated by Django 5.0.6 on 2024-08-05 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('gitlabid', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('gitlabusertoken', models.CharField(max_length=255, unique=True)),
                ('gitlaburl', models.URLField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=240, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('web_url', models.URLField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=200, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.JSONField(blank=True, null=True)),
                ('department', models.JSONField(blank=True, null=True)),
                ('followers', models.JSONField(blank=True, null=True)),
                ('following', models.JSONField(blank=True, null=True)),
                ('date_joined', models.CharField(blank=True, max_length=200, null=True)),
                ('updatedAt', models.CharField(max_length=200, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
