# Generated by Django 5.0.6 on 2024-08-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gitlaburl',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
