# Generated by Django 5.0.6 on 2024-08-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_user_gitlaburl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gitlabid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
